//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stan.SQLData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stan()
        {
            this.Cena = 0;
        }
    
        public int Id { get; set; }
        public string GazdaId { get; set; }
        public short Kvadratura { get; set; }
        public short BrojNaSobi { get; set; }
        public short NaKojSprat { get; set; }
        public bool ImaLift { get; set; }
        public bool ImaKujna { get; set; }
        public bool ImaToalet { get; set; }
        public bool ImaTerasa { get; set; }
        public bool Namesten { get; set; }
        public System.DateTime DatumObjaven { get; set; }
        public string KontaktIme { get; set; }
        public string KontaktBroj { get; set; }
        public string Lokacija { get; set; }
        public string Opis { get; set; }
        public short Cena { get; set; }
    }
}
